<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!--
      Importante:
      dejamos que WPF descubra automáticamente App.xaml,
      MainWindow.xaml, Styles/*.xaml y Pages/*.xaml.
    -->
    <EnableDefaultApplicationDefinition>true</EnableDefaultApplicationDefinition>
    <EnableDefaultPageItems>true</EnableDefaultPageItems>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EvolutionSim\EvolutionSim.csproj" />
  </ItemGroup>

</Project>
